### ISSUE TITLE
String index out of bounds exception

### ISSUE THREAD

**Issue by rsiebert** [rsiebert/TVHClient#266]
Reported by a user via google play store.

Caused by: java.lang.StringIndexOutOfBoundsException: length=74; index=-1
    at java.lang.String.indexAndLength(String.java:294)
    at java.lang.String.substring(String.java:1067)
    at org.tvheadend.tvhclient.ExternalActionActivity.startPlayback(ExternalActionActivity.java:317)
    at org.tvheadend.tvhclient.ExternalActionActivity.initAction(ExternalActionActivity.java:103)
    at org.tvheadend.tvhclient.ExternalActionActivity.onResume(ExternalActionActivity.java:143)

https://github.com/rsiebert/TVHClient/blob/develop/app/src/main/java/org/tvheadend/tvhclient/ExternalActionActivity.java#L336

**Comment by rsiebert** [comment]
Fixed in https://github.com/rsiebert/TVHClient/commit/a43e8ac647acd1a76403f6a91e035c9dcecdc43d
