### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by hurzl** [rsiebert/TVHClient#331]
```
01-10 01:11:38.567 20985-20985/org.tvheadend.tvhclient E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.tvheadend.tvhclient, PID: 20985
                                                                         java.lang.RuntimeException: Unable to resume activity {org.tvheadend.tvhclient/org.tvheadend.tvhclient.activities.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'long org.tvheadend.tvhclient.model.Connection.id' on a null object reference
                                                                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3445)
                                                                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3485)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2748)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6178)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                          Caused by: java.lang.NullPointerException: Attempt to read from field 'long org.tvheadend.tvhclient.model.Connection.id' on a null object reference
                                                                             at org.tvheadend.tvhclient.activities.MainActivity.updateDrawerHeader(MainActivity.java:627)
                                                                             at org.tvheadend.tvhclient.activities.MainActivity.onResume(MainActivity.java:674)
                                                                             at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
                                                                             at android.app.Activity.performResume(Activity.java:6786)
                                                                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3422)
                                                                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3485) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2748) 
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6178) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 

```

**Comment by rsiebert** [comment]
Many commits were pushed. Should be fixed by now.

**Comment by hurzl** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: org.tvheadend.tvhclient, PID: 17906
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:325)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: android.database.sqlite.SQLiteException: Cannot add a NOT NULL column with default value NULL (code 1): , while compiling: ALTER TABLE connections ADD COLUMN wol_enabled INTEGER NOT NULL;
                      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
                      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
                      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                      at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                      at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1686)
                      at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1617)
                      at android.arch.persistence.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:240)
                      at org.tvheadend.tvhclient.data.AppDatabase$10.migrate(AppDatabase.java:409)
                      at android.arch.persistence.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:73)
                      at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:118)
                      at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
                      at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                      at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
                      at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
                      at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)
                      at org.tvheadend.tvhclient.data.dao.ConnectionDao_Impl.loadAllConnectionsSync(ConnectionDao_Impl.java:321)
                      at org.tvheadend.tvhclient.data.repository.ConnectionRepository$LoadAllConnectionsTask.doInBackground(ConnectionRepository.java:109)
                      at org.tvheadend.tvhclient.data.repository.ConnectionRepository$LoadAllConnectionsTask.doInBackground(ConnectionRepository.java:100)
                      at android.os.AsyncTask$2.call(AsyncTask.java:305)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
```

**Comment by rsiebert** [comment]
This issue does not resolve from a released app version.
