### ISSUE TITLE
Version 2.1.0 from 04.02 crashes on Android 4.4

### ISSUE THREAD

**Issue by chpasha** [rsiebert/TVHClient#422]
The app crashes right after installation with nothing configured - the previous version did work

```
java.lang.RuntimeException: Unable to get provider org.tvheadend.tvhclient.features.search.SuggestionProvider: java.lang.ClassNotFoundException: Didn't find class "org.tvheadend.tvhclient.features.search.SuggestionProvider" on path: DexPathList[[zip file "/data/app/org.tvheadend.tvhclient-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.tvheadend.tvhclient-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(20914):        at android.app.ActivityThread.installProvider(ActivityThread.java)
E/AndroidRuntime(20914):        at android.app.ActivityThread.installContentProviders(ActivityThread.java)
E/AndroidRuntime(20914):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
E/AndroidRuntime(20914):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime(20914):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
E/AndroidRuntime(20914):        at android.app.ActivityThread.handleBindApplication(Native Method)
E/AndroidRuntime(20914):        at android.app.ActivityThread.access$1500(ActivityThread.java)
E/AndroidRuntime(20914):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
E/AndroidRuntime(20914):        at android.os.Handler.dispatchMessage(Handler.java)
E/AndroidRuntime(20914):        at android.os.Looper.loop(Looper.java)
E/AndroidRuntime(20914):        at android.app.ActivityThread.main(ActivityThread.java)
E/AndroidRuntime(20914):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(20914):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(20914):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
E/AndroidRuntime(20914):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
E/AndroidRuntime(20914):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(20914): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.tvheadend.tvhclient.features.search.SuggestionProvider" on path: DexPathList[[zip file "/data/app/org.tvheadend.tvhclient-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.tvheadend.tvhclient-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(20914):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(20914):        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(20914):        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(20914):        ... 17 more
W/ActivityManager( 1014):   Force finishing activity org.tvheadend.tvhclient/.features.startup.SplashActivity

```

any ideas?

**Comment by rsiebert** [comment]
This is due to how multidex is handled on older devices. The newer version 2.2.0 currently in beta will fix this.

**Comment by chpasha** [comment]
:+1:

**Comment by rsiebert** [comment]
Version 2.2.0 has just been released

**Comment by chpasha** [comment]
thank you, works as expected
