### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by polyboi** [rsiebert/TVHClient#546]
I apologise if I'm missing something obvious but I keep trying to connect to my tvheadend server but I get "Connection Failed" and "Authentication Failed" messages. I had a look at the log file and it looks like this is the problem...

[C:HtspConnection] [M:run] [L:396]  Exception while processing tcp selection key
java.io.IOException
	at org.tvheadend.htsp.HtspConnection.processTcpSelectionKey(HtspConnection.java:425)
	at org.tvheadend.htsp.HtspConnection.run(HtspConnection.java:367)

I can connect using Kodi with the same credentials but I can't get it to work with TVHClient

I am using the latest docker version of tvheadend as maintained by the linuxserver group.

**Comment by Joerchi** [comment]
Same here. TVHeadend Server running on my Synology NAS, I can connect using KODI (from various devices and Kodi instances) using my credentials but connecting using this Android app leads to "authentication failed". I have also enabled generic user/pass with * on the TVHeadend server just for testing purposes but it does also not yield any success (same error with * as user and password).

**Comment by bitozoid** [comment]
I could authenticate by setting port 9882 to the web URL.

**Comment by janroelofs** [comment]
Some time ago I had the same problem: also could not connect using http://device:9982. 
But now it works again. Maybe tvheadend (running on raspberry pi) has been updated, the version installed now is tvheadend-armv6l/now 4.3-2315\~gab6ea89b1\~buster armhf.
